//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evidence_1264855.Models
{
    using Evidence_1264855.Models.DbMetadata;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(EmployeesType))]
    public partial class Employees
    {
        public int EmployeeID { get; set; }
        public string EmployeePicture { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeePhone { get; set; }
        public int EmployeeDepartment { get; set; }
        public System.DateTime EmployeeJoinDate { get; set; }
        public int BranchID { get; set; }
    
        public virtual Branches Branches { get; set; }
    }
}
